FROM docker.io/nginx:1.13
USER  root
ARG NGINX_TMPL

# Add start script
ADD compose/local/nginx/nginx-start.sh /
RUN chmod +x nginx-start.sh

# Add nginx config file
#THIS THING CANT EXPAND ${NGINX_TMPL} properly for some reason. SHould look into it later. For now I've hard coded the path to the template
ADD compose/local/nginx/nginx.tmpl /

# Add SSL certs to location specified in nginx.conf
ADD compose/local/nginx/*.crt /etc/ssl/certs/
ADD compose/local/nginx/*.key /etc/ssl/private/

CMD ["/nginx-start.sh"]