FROM mapserver/mapserver:v7.4.2

USER root

# See https://github.com/geo-data/mapserver-docker/blob/master/build.sh
# Install the build dependencies.
RUN apt-get update -y && apt-get install -y libfcgi-dev fcgiwrap 
## Removed nginx from apt-get
#nginx

# Set up the Nginx Mapserver configuration.
##### I dont think this is required since we are not running nginx will comment out for now
#DD mapserver.tmpl /etc/nginx/sites-available/mapserver
#RUN ln -s /etc/nginx/sites-available/mapserver /etc/nginx/sites-enabled/mapserver
#RUN rm /etc/nginx/sites-enabled/default

# Set up the run script for starting services.
#Changed ADD to COPY. Supposedly better for build cache. Change back if it doesnt work
COPY ./compose/local/mapserver/mapserver-start.sh /usr/local/bin
RUN chmod +x /usr/local/bin/mapserver-start.sh

EXPOSE 80

# Start the fcgi and web servers.
CMD ["/usr/local/bin/mapserver-start.sh"]
