# version: '3' TODO: Update version
version: "2.2"

volumes:
  stoqs_local_postgres_data: {}
  stoqs_local_postgres_data_backups: {}
  static-files:
  media-files:

services:
  stoqs:
    image: mbari/stoqs
    build:
      context: .
      dockerfile: ./compose/local/stoqs/Dockerfile-stoqs
    volumes:
      - /tmp/docker_stoqs_vols/maps:${MAPFILE_DIR}
      - /tmp/docker_stoqs_vols/stoqs_root:/root
      - /tmp/docker_stoqs_vols/nginx:/usr/share/nginx
      - /tmp/docker_stoqs_vols/pg_dumps:/srv/media-files/pg_dumps
      - ${PWD}:/srv
      - static-files:/srv/static-files
      - media-files:/srv/media-files
    environment:
      - DATABASE_URL
      - DATABASE_SUPERUSER_URL
      - PGHOST
      - POSTGRES_PASSWORD
      - MAPSERVER_HOST
      - URL_MAPFILE_DIR=/maps
      - STATIC_URL=/static/
      - STATIC_ROOT=/srv/static-files
      - MEDIA_URL=/media/
      - MEDIA_ROOT=/srv/media-files
      - NGINX_SERVER_NAME
      - UWSGI_READ_TIMEOUT
      - DJANGO_DEBUG
      - USER
    container_name: stoqs
    depends_on:
      - mapserver
      - postgis
    ports:
      - "8888:8888"
    # Expose port 8000 if PRODUCTION=false - Note: PRODUCTION=false doesn't work (March 2019)
    ##  - "8000:8000"
    restart: always
    env_file:
      - .envs/.local/.stoqs/.env

  # django:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   image: stoqs_local_django
  #   container_name: stoqs_local_django
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - .:/app:z
  #   env_file:
  #     - ./.envs/.local/.django
  #     - ./.envs/.local/.postgres
  #   ports:
  #     - "8000:8000"
  #   command: /start

  postgis:
    image: mbari/stoqs-postgis
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile-postgis
    volumes:
      - /tmp/docker_stoqs_vols/pgdata:/var/lib/postgresql/data
      - /tmp/docker_stoqs_vols/pg_waldir:/var/lib/postgresql/waldir
      - ./postgres15-stoqs.conf:/etc/postgresql.conf
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5432:5432"
    # Set user for deployment on MacOS, assign HOST_UID=<result of `id -u`> in your .env file
    ##user: ${HOST_UID}
    environment:
      - POSTGRES_PASSWORD
      - STOQSADM_PASSWORD
        # https://github.com/docker-library/postgres/issues/263#issuecomment-280504406
      - PGDATA=/var/lib/postgresql/data/db_files
      - POSTGRES_INITDB_WALDIR=/var/lib/postgresql/waldir/wal_files
    container_name: stoqs-postgis
    oom_kill_disable: true
    restart: always
    shm_size: 1g
    env_file:
      - .envs/.local/.stoqs/.env

  # postgres:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/postgres/Dockerfile
  #   image: stoqs_production_postgres
  #   container_name: stoqs_local_postgres
  #   volumes:
  #     - stoqs_local_postgres_data:/var/lib/postgresql/data
  #     - stoqs_local_postgres_data_backups:/backups
  #   env_file:
  #     - ./.envs/.local/.postgres

  mapserver:
    image: mbari/stoqs-mapserver
    build:
      context: .
      dockerfile: ./compose/local/mapserver/Dockerfile-mapserver
    volumes:
      - /tmp/docker_stoqs_vols/maps:/maps:ro
    container_name: stoqs-mapserver
    # Expose port 80 if PRODUCTION=false - Note: PRODUCTION=false doesn't work (March 2019)
    ##ports:
    ##  - "80:80"
    restart: always
    env_file:
      - .envs/.local/.stoqs/.env

  # docs:
  #   image: stoqs_local_docs
  #   container_name: stoqs_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./stoqs:/app/stoqs:z
  #   ports:
  #     - "9000:9000"
  #   command: /start-docs

  # Disable nginx service if PRODUCTION=false - Note: PRODUCTION=false doesn't work (March 2019)
  # nginx:
  #   image: mbari/stoqs-nginx
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-nginx
  #   volumes:
  #     - ${STOQS_VOLS_DIR}/html:/srv/html
  #     - ${STOQS_VOLS_DIR}/pg_dumps:/srv/media-files/pg_dumps
  #     - static-files:/srv/static-files
  #     - media-files:/srv/media-files
  #   environment:
  #     - NGINX_TMPL=${NGINX_TMPL}
  #   container_name: stoqs-nginx
  #   ports:
  #     - "80:80"
  #     - "8000:8000"
  #     - "443:443"
  #   depends_on:
  #     - stoqs
  #   restart: always
  #   env_file:
  #     - ./.env
